version: '3'

services:
  ghosthost-bot:
    image: 245045109982.dkr.ecr.eu-west-2.amazonaws.com/ghosthost:latest
    volumes:
      - /mnt/efs/clients/${USERNAME}:/opt/PhantomBot_data
    environment:
      PHANTOMBOT_USER: ${BOT_NAME}
      PHANTOMBOT_OAUTH: ${BOT_OAUTH}
      PHANTOMBOT_CHANNEL: ${USER_NAME}
      PHANTOMBOT_APIOAUTH: ${USER_OAUTH}
      PHANTOMBOT_PANELUSER: ${PANEL_USER_NAME}
      PHANTOMBOT_PANELPASSWORD: ${PANEL_PASSWORD}
      PHANTOMBOT_USEHTTPS: "false"
    networks:
       - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 100M
      labels:
      - traefik.http.services.gh-${USER_NAME}.loadbalancer.server.port=25000
      - traefik.http.routers.gh-${USER_NAME}.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.gh-${USER_NAME}.entrypoints=http
      - traefik.http.routers.gh-${USER_NAME}.entrypoints=https
      - traefik.http.routers.gh-${USER_NAME}.tls=true
      - traefik.http.routers.gh-${USER_NAME}.tls.certresolver=le
      - traefik.http.middlewares.gh-${USER_NAME}.redirectscheme.scheme=https
      - traefik.http.middlewares.gh-${USER_NAME}.redirectscheme.permanent=true
